#!/usr/bin/env bash
# Envoyer une requête ping à une adresse IP transmise en argument, 5 fois
if [ -z "$1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi
ping -c 5 "$1"
